--Usuários

CREATE USER user1 WITH PASSWORD '123' LOGIN;
CREATE USER user2 WITH PASSWORD '321' LOGIN;
CREATE USER user3 WITH PASSWORD '012' LOGIN;

CREATE GROUP grpA;
CREATE GROUP grpB;

ALTER GROUP grpA ADD USER user1, user2;
ALTER GROUP grpB ADD USER user3;

GRANT USAGE ON SCHEMA sch01 TO grpA;
GRANT USAGE ON SCHEMA sch01 TO grpB;

REVOKE ALL ON SCHEMA sch01 FROM grpB;
REVOKE INSERT ON sch01.teste FROM grpA;
